In [1]:
import pandas as pd
import numpy as np

## pandas Series: .unique() & .nunique()

In [15]:
data = pd.read_csv('Location.csv')
location_data = data.copy()
dataframe_to_series = location_data.squeeze()
dataframe_to_series

0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [16]:
type(dataframe_to_series)

pandas.core.series.Series

In [17]:
dataframe_to_series.describe()

count            1043
unique            296
top       Location 25
freq               31
Name: Location, dtype: object

In [18]:
len(dataframe_to_series)

1043

In [19]:
dataframe_to_series.unique() # It gives unique values

array(['Location 3', 'Location 6', 'Location 8', 'Location 26',
       'Location 34', 'Location 25', 'Location 46', 'Location 156',
       'Location 21', 'Location 13', 'Location 579', 'Location 602',
       'Location 10', 'Location 44', 'Location 30', 'Location 48',
       'Location 196', 'Location 64', 'Location 91', 'Location 62',
       'Location 75', 'Location 42', 'Location 233', 'Location 95',
       'Location 78', 'Location 61', 'Location 87', 'Location 19',
       'Location 115', 'Location 350', 'Location 377', 'Location 17',
       'Location 113', 'Location 81', 'Location 58', 'Location 212',
       'Location 53', 'Location 337', 'Location 41', 'Location 632',
       'Location 73', 'Location 214', 'Location 218', 'Location 38',
       'Location 172', 'Location 197', 'Location 101', 'Location 185',
       'Location 129', 'Location 235', 'Location 142', 'Location 50',
       'Location 76', 'Location 11', 'Location 33', 'Location 22',
       'Location 145', 'Location 203', 'Loca

In [21]:
dataframe_to_series.nunique() # It return number of unique values

296

In [22]:
type(dataframe_to_series.unique())

numpy.ndarray

In [23]:
type(dataframe_to_series.nunique())

int

## pandas Series: Converting Series into Arrays (.values, .array, .to_numpy())

In [24]:
prices_per_category = pd.Series({'Product A': 22250, 'Product B' : 16600, 'Product C':15600})
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [26]:
prices_per_category.values

array([22250, 16600, 15600], dtype=int64)

In [27]:
type(prices_per_category.values)

numpy.ndarray

In [28]:
prices_per_category.array

<PandasArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [29]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.PandasArray

In [33]:
prices_per_category.to_numpy()

array([22250, 16600, 15600], dtype=int64)

In [32]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [34]:
prices_per_category.values[0]

22250

In [35]:
type(prices_per_category.values[0])

numpy.int64

In [36]:
prices_per_category.array[0]

22250

In [37]:
type(prices_per_category.array[0])

numpy.int64

In [39]:
prices_per_category.to_numpy()[0]

22250

In [40]:
type(prices_per_category.to_numpy()[0])

numpy.int64

## pandas Series: .sort_values()

In [41]:
number = pd.Series([12,34,1,452,12])
number

0     12
1     34
2      1
3    452
4     12
dtype: int64

In [42]:
number.sort_values()

2      1
0     12
4     12
1     34
3    452
dtype: int64

In [43]:
number.sort_values(ascending=True)

2      1
0     12
4     12
1     34
3    452
dtype: int64

In [44]:
number.sort_values(ascending= False)

3    452
1     34
0     12
4     12
2      1
dtype: int64

In [47]:
dataframe_to_series

0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [46]:
dataframe_to_series.sort_values()

637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [48]:
dataframe_to_series.sort_values(ascending=True)

637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [49]:
dataframe_to_series.sort_values(ascending=False)

372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
          ...     
202    Location 10
298    Location 10
637     Location 1
884     Location 1
465     Location 1
Name: Location, Length: 1043, dtype: object

## Attribute and Method Chaining

In [50]:
dataframe_to_series.head()

0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [51]:
dataframe_to_series.index

RangeIndex(start=0, stop=1043, step=1)

In [52]:
dataframe_to_series.name

'Location'

In [53]:
dataframe_to_series.index.name

In [54]:
dataframe_to_series.index.name = 'Index'

In [55]:
dataframe_to_series

Index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [56]:
dataframe_to_series.index.name

'Index'

In [57]:
dataframe_to_series.sort_values()

Index
637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [58]:
dataframe_to_series.sort_values().head(5)

Index
637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
Name: Location, dtype: object

In [59]:
dataframe_to_series.sort_values().tail(5)

Index
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, dtype: object

In [62]:
dataframe_to_series.index

RangeIndex(start=0, stop=1043, step=1, name='Index')

In [64]:
dataframe_to_series.index.values

array([   0,    1,    2, ..., 1040, 1041, 1042], dtype=int64)

## pandas Series: .sort_index() 

In [65]:
dataframe_to_series.head()

Index
0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [68]:
location_data_sv = dataframe_to_series.sort_values(ascending=False)
location_data_sv.head()

Index
372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
Name: Location, dtype: object

In [69]:
location_data_sv.index

Int64Index([ 372,  757,  128,  482,  271,  669,  612,   29,  518,  598,
            ...
             904,  912, 1010,   14,  716,  202,  298,  637,  884,  465],
           dtype='int64', name='Index', length=1043)

In [70]:
location_data_sv.index.sort_values()

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042],
           dtype='int64', name='Index', length=1043)

In [71]:
location_data_sv.head()

Index
372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
Name: Location, dtype: object

In [72]:
location_data_sv.sort_index()

Index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [73]:
location_data_sv

Index
372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
          ...     
202    Location 10
298    Location 10
637     Location 1
884     Location 1
465     Location 1
Name: Location, Length: 1043, dtype: object

In [74]:
location_data_sv = location_data_sv.sort_index(ascending=True)
location_data_sv

Index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object